server:
  port: 8024
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/data-interaction?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 888888
    driver-class-name: com.mysql.cj.jdbc.Driver
  mqtt:
    clientid: testcqaevef
    host: tcp://118.31.64.160:1883
    password: qq2002123
    timeout: 1000
    keepalive: 10
#最大连接数
http:
    maxTotal: 100
    #并发数
    defaultMaxPerRoute: 20
    #创建连接的最长时间
    connectTimeout: 1000
    #从连接池中获取到连接的最长时间
    connectionRequestTimeout: 500
    #数据传输的最长时间
    socketTimeout: 10000
    #提交请求前测试连接是否可用
    staleConnectionCheckEnabled: true
    #可用空闲连接过期时间,重用空闲连接时会先检查是否空闲时间超过这个时间，如果超过，释放socket重新建立
    validateAfterInactivity: 3000000