server:
  port: 8024
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/data-interaction?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 888888
    driver-class-name: com.mysql.cj.jdbc.Driver
  mqtt:
    clientid: mqttjs_cloud
    host: tcp://118.31.64.160:1883
    password: qq2002123
    timeout: 1000
    keepalive: 10