server:
  port: 8024
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/data-interaction?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 888888
    driver-class-name: com.mysql.cj.jdbc.Driver
  mqtt:
#    username: admin							# 账号
#    password: public						# 密码
    host-url: mqtt://118.31.64.160:1883				# mqtt连接tcp地址
    client-id: spring							# 客户端Id，每个启动的id要不同
    default-topic: test						# 默认主题
    timeout: 100							# 超时时间
    keepalive: 60							# 保持连接数
