server:
  port: 8024
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/data-interaction?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 888888
    driver-class-name: com.mysql.cj.jdbc.Driver
